from Models.Member import Member
from Repository.MemberRepository import MemberRepository


class DatabaseSeeder:

    @staticmethod
    def members():
        members = [{"firstName": "Tammara", "lastName": "Gwyneth", "gender": "m", "weight": 68, "city": "Pittsburgh",
                    "houseNumber": "0604", "streetName": "Cardinal", "zipCode": "1234AA",
                    "emailAddress": "tgwyneth0@hubpages.com", "phoneNumber": 12726362, "age": 35},
                   {"firstName": "Robinette", "lastName": "Sparks", "gender": "m", "weight": 58, "city": "Subotica",
                    "houseNumber": "96343", "streetName": "Stuart", "zipCode": "1234AA",
                    "emailAddress": "rsparks1@yellowbook.com", "phoneNumber": 37582026, "age": 26},
                   {"firstName": "Christophe", "lastName": "Shillitoe", "gender": "m", "weight": 53,
                    "city": "Jargalant", "houseNumber": "51225", "streetName": "Sheridan", "zipCode": "1234AA",
                    "emailAddress": "cshillitoe2@accuweather.com", "phoneNumber": 54212628, "age": 37},
                   {"firstName": "Ingamar", "lastName": "Clancy", "gender": "m", "weight": 93, "city": "San Luis",
                    "houseNumber": "4", "streetName": "Fisk", "zipCode": "1234AA",
                    "emailAddress": "iclancy3@webeden.co.uk", "phoneNumber": 41231375, "age": 64},
                   {"firstName": "Martyn", "lastName": "Gilburt", "gender": "m", "weight": 92, "city": "Pameungpeuk",
                    "houseNumber": "8040", "streetName": "Mccormick", "zipCode": "1234AA",
                    "emailAddress": "mgilburt4@usa.gov", "phoneNumber": 80062910, "age": 80},
                   {"firstName": "Winslow", "lastName": "Satyford", "gender": "m", "weight": 60, "city": "Aqtöbe",
                    "houseNumber": "84", "streetName": "Debra", "zipCode": "1234AA",
                    "emailAddress": "wsatyford5@lycos.com", "phoneNumber": 56617369, "age": 36},
                   {"firstName": "Early", "lastName": "McAlarney", "gender": "m", "weight": 60, "city": "Pocora",
                    "houseNumber": "3", "streetName": "Main", "zipCode": "1234AA",
                    "emailAddress": "emcalarney6@fastcompany.com", "phoneNumber": 18204587, "age": 18},
                   {"firstName": "Brigida", "lastName": "Devine", "gender": "m", "weight": 58, "city": "Desa Borogojol",
                    "houseNumber": "54284", "streetName": "Del Sol", "zipCode": "1234AA",
                    "emailAddress": "bdevine7@bravesites.com", "phoneNumber": 34472452, "age": 36},
                   {"firstName": "Josephina", "lastName": "Iozefovich", "gender": "m", "weight": 57, "city": "Lemery",
                    "houseNumber": "4", "streetName": "Moland", "zipCode": "1234AA",
                    "emailAddress": "jiozefovich8@adobe.com", "phoneNumber": 87786624, "age": 47},
                   {"firstName": "Laurent", "lastName": "Rewcastle", "gender": "m", "weight": 92, "city": "Jelisavac",
                    "houseNumber": "7", "streetName": "Valley Edge", "zipCode": "1234AA",
                    "emailAddress": "lrewcastle9@studiopress.com", "phoneNumber": 77534440, "age": 42},
                   {"firstName": "Trevar", "lastName": "Guymer", "gender": "m", "weight": 88, "city": "Kebon",
                    "houseNumber": "47228", "streetName": "Burning Wood", "zipCode": "1234AA",
                    "emailAddress": "tguymera@w3.org", "phoneNumber": 99536777, "age": 68},
                   {"firstName": "Lancelot", "lastName": "Cabera", "gender": "m", "weight": 85, "city": "Bowen Island",
                    "houseNumber": "69207", "streetName": "Meadow Vale", "zipCode": "1234AA",
                    "emailAddress": "lcaberab@army.mil", "phoneNumber": 78739110, "age": 79},
                   {"firstName": "Glenda", "lastName": "Meddemmen", "gender": "m", "weight": 71, "city": "Gbarnga",
                    "houseNumber": "12507", "streetName": "Forster", "zipCode": "1234AA",
                    "emailAddress": "gmeddemmenc@altervista.org", "phoneNumber": 41796149, "age": 53},
                   {"firstName": "Maxi", "lastName": "Halliburton", "gender": "m", "weight": 86, "city": "Jinka",
                    "houseNumber": "0", "streetName": "Red Cloud", "zipCode": "1234AA",
                    "emailAddress": "mhalliburtond@blogger.com", "phoneNumber": 43607155, "age": 68},
                   {"firstName": "Nicoli", "lastName": "Isworth", "gender": "m", "weight": 54, "city": "Kuanheum",
                    "houseNumber": "213", "streetName": "Algoma", "zipCode": "1234AA",
                    "emailAddress": "nisworthe@icio.us", "phoneNumber": 42003589, "age": 59},
                   {"firstName": "Kasey", "lastName": "Lancastle", "gender": "m", "weight": 77, "city": "Liubo",
                    "houseNumber": "071", "streetName": "Pine View", "zipCode": "1234AA",
                    "emailAddress": "klancastlef@businesswire.com", "phoneNumber": 39931805, "age": 52},
                   {"firstName": "Adele", "lastName": "Pottle", "gender": "m", "weight": 89, "city": "Gampola",
                    "houseNumber": "7", "streetName": "Hanson", "zipCode": "1234AA",
                    "emailAddress": "apottleg@prlog.org", "phoneNumber": 52852280, "age": 55},
                   {"firstName": "Bryanty", "lastName": "Cicci", "gender": "m", "weight": 63, "city": "Sibiti",
                    "houseNumber": "7", "streetName": "Comanche", "zipCode": "1234AA",
                    "emailAddress": "bciccih@hc360.com", "phoneNumber": 83160050, "age": 19},
                   {"firstName": "Mano", "lastName": "Trawin", "gender": "m", "weight": 59, "city": "Kalangala",
                    "houseNumber": "83", "streetName": "Mitchell", "zipCode": "1234AA",
                    "emailAddress": "mtrawini@pcworld.com", "phoneNumber": 92687496, "age": 35},
                   {"firstName": "Hamel", "lastName": "Mottinelli", "gender": "m", "weight": 55, "city": "Dangcalan",
                    "houseNumber": "6", "streetName": "David", "zipCode": "1234AA",
                    "emailAddress": "hmottinellij@goodreads.com", "phoneNumber": 24958516, "age": 53},
                   {"firstName": "Robinson", "lastName": "Cazereau", "gender": "m", "weight": 64, "city": "Huangchuan",
                    "houseNumber": "5", "streetName": "Emmet", "zipCode": "1234AA",
                    "emailAddress": "rcazereauk@elegantthemes.com", "phoneNumber": 96191123, "age": 80},
                   {"firstName": "Hilliard", "lastName": "Veall", "gender": "m", "weight": 87, "city": "Borlänge",
                    "houseNumber": "689", "streetName": "Mccormick", "zipCode": "1234AA",
                    "emailAddress": "hvealll@chronoengine.com", "phoneNumber": 13531437, "age": 19},
                   {"firstName": "Henderson", "lastName": "Deverell", "gender": "m", "weight": 86, "city": "Loughrea",
                    "houseNumber": "9", "streetName": "Stang", "zipCode": "1234AA",
                    "emailAddress": "hdeverellm@usatoday.com", "phoneNumber": 79546972, "age": 36},
                   {"firstName": "Evania", "lastName": "Leethem", "gender": "m", "weight": 68, "city": "Roscoff",
                    "houseNumber": "9", "streetName": "Fieldstone", "zipCode": "1234AA",
                    "emailAddress": "eleethemn@over-blog.com", "phoneNumber": 67671859, "age": 80},
                   {"firstName": "Frank", "lastName": "Morratt", "gender": "m", "weight": 62, "city": "Kárystos",
                    "houseNumber": "0556", "streetName": "8th", "zipCode": "1234AA",
                    "emailAddress": "fmorratto@wikispaces.com", "phoneNumber": 41578667, "age": 71},
                   {"firstName": "Kelby", "lastName": "Weare", "gender": "m", "weight": 59, "city": "Nkhotakota",
                    "houseNumber": "2484", "streetName": "Autumn Leaf", "zipCode": "1234AA",
                    "emailAddress": "kwearep@narod.ru", "phoneNumber": 46189055, "age": 34},
                   {"firstName": "Aura", "lastName": "Mathelon", "gender": "m", "weight": 91, "city": "Veřovice",
                    "houseNumber": "9", "streetName": "Johnson", "zipCode": "1234AA",
                    "emailAddress": "amathelonq@mlb.com", "phoneNumber": 17708151, "age": 74},
                   {"firstName": "Lorelle", "lastName": "Fellon", "gender": "m", "weight": 56, "city": "Neikeng",
                    "houseNumber": "565", "streetName": "Nancy", "zipCode": "1234AA",
                    "emailAddress": "lfellonr@nps.gov", "phoneNumber": 97574491, "age": 26},
                   {"firstName": "Cozmo", "lastName": "Collet", "gender": "m", "weight": 86, "city": "Sa‘sa‘",
                    "houseNumber": "23078", "streetName": "Valley Edge", "zipCode": "1234AA",
                    "emailAddress": "ccollets@webs.com", "phoneNumber": 87483342, "age": 21},
                   {"firstName": "Grange", "lastName": "Hornig", "gender": "m", "weight": 84, "city": "Semënov",
                    "houseNumber": "36", "streetName": "Lillian", "zipCode": "1234AA",
                    "emailAddress": "ghornigt@admin.ch", "phoneNumber": 30278726, "age": 47},
                   {"firstName": "Priscilla", "lastName": "Harrill", "gender": "m", "weight": 82, "city": "Foča",
                    "houseNumber": "50829", "streetName": "Derek", "zipCode": "1234AA",
                    "emailAddress": "pharrillu@smugmug.com", "phoneNumber": 24117221, "age": 52},
                   {"firstName": "Carley", "lastName": "Cocozza", "gender": "m", "weight": 86, "city": "Zhanbei",
                    "houseNumber": "33", "streetName": "Stoughton", "zipCode": "1234AA",
                    "emailAddress": "ccocozzav@desdev.cn", "phoneNumber": 54249240, "age": 33},
                   {"firstName": "Ketti", "lastName": "Fetteplace", "gender": "m", "weight": 65, "city": "Aplahoué",
                    "houseNumber": "79", "streetName": "Lyons", "zipCode": "1234AA",
                    "emailAddress": "kfetteplacew@theguardian.com", "phoneNumber": 39879927, "age": 22},
                   {"firstName": "Pearl", "lastName": "Bonifazio", "gender": "m", "weight": 57, "city": "Zhujiachang",
                    "houseNumber": "12", "streetName": "Tomscot", "zipCode": "1234AA",
                    "emailAddress": "pbonifaziox@cnet.com", "phoneNumber": 84298426, "age": 52},
                   {"firstName": "Clemmy", "lastName": "Khristoforov", "gender": "m", "weight": 60, "city": "Tanudan",
                    "houseNumber": "948", "streetName": "Rieder", "zipCode": "1234AA",
                    "emailAddress": "ckhristoforovy@hibu.com", "phoneNumber": 44156842, "age": 44},
                   {"firstName": "Marinna", "lastName": "Benech", "gender": "m", "weight": 88,
                    "city": "São Brás de Alportel", "houseNumber": "10", "streetName": "Debra", "zipCode": "1234AA",
                    "emailAddress": "mbenechz@ow.ly", "phoneNumber": 26304647, "age": 19},
                   {"firstName": "Wynn", "lastName": "Swansbury", "gender": "m", "weight": 93, "city": "Hawassa",
                    "houseNumber": "64539", "streetName": "Brickson Park", "zipCode": "1234AA",
                    "emailAddress": "wswansbury10@plala.or.jp", "phoneNumber": 51264185, "age": 63},
                   {"firstName": "Bealle", "lastName": "De Lasci", "gender": "m", "weight": 86, "city": "Hekou",
                    "houseNumber": "91397", "streetName": "Oakridge", "zipCode": "1234AA",
                    "emailAddress": "bdelasci11@webnode.com", "phoneNumber": 79040794, "age": 68},
                   {"firstName": "Celina", "lastName": "Buchett", "gender": "m", "weight": 92,
                    "city": "La Paz de Oriente", "houseNumber": "05565", "streetName": "Sloan", "zipCode": "1234AA",
                    "emailAddress": "cbuchett12@amazon.de", "phoneNumber": 22378119, "age": 78},
                   {"firstName": "Ambur", "lastName": "Alldre", "gender": "m", "weight": 70, "city": "Wafang",
                    "houseNumber": "4", "streetName": "Miller", "zipCode": "1234AA",
                    "emailAddress": "aalldre13@scientificamerican.com", "phoneNumber": 60919263, "age": 49},
                   {"firstName": "Jacquie", "lastName": "Deniso", "gender": "m", "weight": 67, "city": "Sidenreng",
                    "houseNumber": "7", "streetName": "Superior", "zipCode": "1234AA",
                    "emailAddress": "jdeniso14@1688.com", "phoneNumber": 85317468, "age": 79},
                   {"firstName": "Dallas", "lastName": "Brandom", "gender": "m", "weight": 83, "city": "Denov",
                    "houseNumber": "9", "streetName": "Ohio", "zipCode": "1234AA",
                    "emailAddress": "dbrandom15@123-reg.co.uk", "phoneNumber": 70873463, "age": 45},
                   {"firstName": "Ferdie", "lastName": "Mattisssen", "gender": "m", "weight": 50, "city": "Xiaoshun",
                    "houseNumber": "2", "streetName": "Express", "zipCode": "1234AA",
                    "emailAddress": "fmattisssen16@canalblog.com", "phoneNumber": 18560101, "age": 62},
                   {"firstName": "Petronille", "lastName": "Munt", "gender": "m", "weight": 55,
                    "city": "Pedraza La Vieja", "houseNumber": "6", "streetName": "Burning Wood", "zipCode": "1234AA",
                    "emailAddress": "pmunt17@webeden.co.uk", "phoneNumber": 73991108, "age": 67},
                   {"firstName": "Abie", "lastName": "Claibourn", "gender": "m", "weight": 52,
                    "city": "Blagoveshchensk", "houseNumber": "747", "streetName": "Kensington", "zipCode": "1234AA",
                    "emailAddress": "aclaibourn18@msn.com", "phoneNumber": 89032741, "age": 70},
                   {"firstName": "Sid", "lastName": "Lulham", "gender": "m", "weight": 54, "city": "Bambali",
                    "houseNumber": "28329", "streetName": "Oak", "zipCode": "1234AA",
                    "emailAddress": "slulham19@sohu.com", "phoneNumber": 25429201, "age": 33},
                   {"firstName": "Ernestine", "lastName": "MacGeaney", "gender": "m", "weight": 68, "city": "Dallas",
                    "houseNumber": "028", "streetName": "Summerview", "zipCode": "1234AA",
                    "emailAddress": "emacgeaney1a@telegraph.co.uk", "phoneNumber": 14209216, "age": 32},
                   {"firstName": "Arte", "lastName": "Whightman", "gender": "m", "weight": 54, "city": "Baoshan",
                    "houseNumber": "049", "streetName": "Sullivan", "zipCode": "1234AA",
                    "emailAddress": "awhightman1b@is.gd", "phoneNumber": 39182206, "age": 40},
                   {"firstName": "Merry", "lastName": "Akrigg", "gender": "m", "weight": 59, "city": "Borovo",
                    "houseNumber": "21483", "streetName": "Amoth", "zipCode": "1234AA",
                    "emailAddress": "makrigg1c@simplemachines.org", "phoneNumber": 45446278, "age": 49},
                   {"firstName": "Gary", "lastName": "Pittam", "gender": "m", "weight": 66, "city": "Pyhäranta",
                    "houseNumber": "668", "streetName": "Petterle", "zipCode": "1234AA",
                    "emailAddress": "gpittam1d@reverbnation.com", "phoneNumber": 90447878, "age": 32},
                   {"firstName": "Genny", "lastName": "Wace", "gender": "m", "weight": 52, "city": "Wuxihe",
                    "houseNumber": "18", "streetName": "Bartelt", "zipCode": "1234AA",
                    "emailAddress": "gwace1e@trellian.com", "phoneNumber": 15435834, "age": 31},
                   {"firstName": "Britta", "lastName": "Penwright", "gender": "m", "weight": 59, "city": "Tamboril",
                    "houseNumber": "449", "streetName": "Pleasure", "zipCode": "1234AA",
                    "emailAddress": "bpenwright1f@hud.gov", "phoneNumber": 62528366, "age": 37},
                   {"firstName": "Milzie", "lastName": "Labone", "gender": "m", "weight": 98, "city": "Cái Dầu",
                    "houseNumber": "01", "streetName": "Waxwing", "zipCode": "1234AA",
                    "emailAddress": "mlabone1g@house.gov", "phoneNumber": 47611395, "age": 38},
                   {"firstName": "Marshal", "lastName": "Schoolfield", "gender": "m", "weight": 51, "city": "Owase",
                    "houseNumber": "71715", "streetName": "Anderson", "zipCode": "1234AA",
                    "emailAddress": "mschoolfield1h@newyorker.com", "phoneNumber": 38173278, "age": 47},
                   {"firstName": "Haslett", "lastName": "Grocutt", "gender": "m", "weight": 66, "city": "Doong",
                    "houseNumber": "42", "streetName": "Jackson", "zipCode": "1234AA",
                    "emailAddress": "hgrocutt1i@tripod.com", "phoneNumber": 25556013, "age": 36},
                   {"firstName": "Jania", "lastName": "Alderman", "gender": "m", "weight": 78, "city": "Marina",
                    "houseNumber": "220", "streetName": "Oak", "zipCode": "1234AA",
                    "emailAddress": "jalderman1j@chron.com", "phoneNumber": 27219033, "age": 54},
                   {"firstName": "Malcolm", "lastName": "McCarroll", "gender": "m", "weight": 51, "city": "Itupeva",
                    "houseNumber": "251", "streetName": "Melrose", "zipCode": "1234AA",
                    "emailAddress": "mmccarroll1k@symantec.com", "phoneNumber": 16363196, "age": 33},
                   {"firstName": "Rosella", "lastName": "Casoni", "gender": "m", "weight": 80,
                    "city": "Aix-en-Provence", "houseNumber": "823", "streetName": "Sommers", "zipCode": "1234AA",
                    "emailAddress": "rcasoni1l@wiley.com", "phoneNumber": 23325889, "age": 62},
                   {"firstName": "Horacio", "lastName": "Sabatier", "gender": "m", "weight": 77,
                    "city": "Castlebellingham", "houseNumber": "7", "streetName": "West", "zipCode": "1234AA",
                    "emailAddress": "hsabatier1m@barnesandnoble.com", "phoneNumber": 46257898, "age": 78},
                   {"firstName": "Dot", "lastName": "Scutt", "gender": "m", "weight": 65, "city": "Bohutín",
                    "houseNumber": "6", "streetName": "Northview", "zipCode": "1234AA",
                    "emailAddress": "dscutt1n@seattletimes.com", "phoneNumber": 79602006, "age": 28},
                   {"firstName": "Hillel", "lastName": "Dalziell", "gender": "m", "weight": 50, "city": "Alenquer",
                    "houseNumber": "38198", "streetName": "Nelson", "zipCode": "1234AA",
                    "emailAddress": "hdalziell1o@list-manage.com", "phoneNumber": 93608869, "age": 80},
                   {"firstName": "Coretta", "lastName": "Maxworthy", "gender": "m", "weight": 51, "city": "Tsarychanka",
                    "houseNumber": "021", "streetName": "Schiller", "zipCode": "1234AA",
                    "emailAddress": "cmaxworthy1p@berkeley.edu", "phoneNumber": 91229021, "age": 70},
                   {"firstName": "Haze", "lastName": "Ruttgers", "gender": "m", "weight": 73, "city": "Embu",
                    "houseNumber": "46", "streetName": "Quincy", "zipCode": "1234AA",
                    "emailAddress": "hruttgers1q@bing.com", "phoneNumber": 20199326, "age": 64},
                   {"firstName": "Issie", "lastName": "Baudouin", "gender": "m", "weight": 71,
                    "city": "San Pedro Carchá", "houseNumber": "3644", "streetName": "Towne", "zipCode": "1234AA",
                    "emailAddress": "ibaudouin1r@dagondesign.com", "phoneNumber": 32236031, "age": 43},
                   {"firstName": "Koral", "lastName": "Stronough", "gender": "m", "weight": 85, "city": "Shengli",
                    "houseNumber": "36", "streetName": "Eastlawn", "zipCode": "1234AA",
                    "emailAddress": "kstronough1s@abc.net.au", "phoneNumber": 36781179, "age": 70},
                   {"firstName": "Jerome", "lastName": "Wrenn", "gender": "m", "weight": 59, "city": "Matango",
                    "houseNumber": "22", "streetName": "Northwestern", "zipCode": "1234AA",
                    "emailAddress": "jwrenn1t@wikispaces.com", "phoneNumber": 87894771, "age": 57},
                   {"firstName": "Lianna", "lastName": "Jeaycock", "gender": "m", "weight": 73, "city": "Majiao",
                    "houseNumber": "7616", "streetName": "Waubesa", "zipCode": "1234AA",
                    "emailAddress": "ljeaycock1u@wix.com", "phoneNumber": 43203126, "age": 20},
                   {"firstName": "Norrie", "lastName": "Clashe", "gender": "m", "weight": 100, "city": "Kallithéa",
                    "houseNumber": "9", "streetName": "Petterle", "zipCode": "1234AA",
                    "emailAddress": "nclashe1v@harvard.edu", "phoneNumber": 44184767, "age": 54},
                   {"firstName": "Wendall", "lastName": "Marlowe", "gender": "m", "weight": 67, "city": "Białobrzegi",
                    "houseNumber": "438", "streetName": "Karstens", "zipCode": "1234AA",
                    "emailAddress": "wmarlowe1w@behance.net", "phoneNumber": 96386230, "age": 47},
                   {"firstName": "Rudy", "lastName": "Sonley", "gender": "m", "weight": 67, "city": "Wellington",
                    "houseNumber": "95556", "streetName": "Hudson", "zipCode": "1234AA",
                    "emailAddress": "rsonley1x@cargocollective.com", "phoneNumber": 97387479, "age": 32},
                   {"firstName": "Ulrike", "lastName": "MacCrann", "gender": "m", "weight": 65, "city": "Conner",
                    "houseNumber": "569", "streetName": "Northport", "zipCode": "1234AA",
                    "emailAddress": "umaccrann1y@abc.net.au", "phoneNumber": 17966999, "age": 36},
                   {"firstName": "Penni", "lastName": "Plaunch", "gender": "m", "weight": 93, "city": "Shanting",
                    "houseNumber": "334", "streetName": "Cardinal", "zipCode": "1234AA",
                    "emailAddress": "pplaunch1z@homestead.com", "phoneNumber": 63671873, "age": 46},
                   {"firstName": "Taddeo", "lastName": "Sheppey", "gender": "m", "weight": 50, "city": "Las Vegas",
                    "houseNumber": "97842", "streetName": "Morningstar", "zipCode": "1234AA",
                    "emailAddress": "tsheppey20@house.gov", "phoneNumber": 27657154, "age": 50},
                   {"firstName": "Pam", "lastName": "MacNair", "gender": "m", "weight": 80, "city": "Lubao",
                    "houseNumber": "0", "streetName": "Paget", "zipCode": "1234AA",
                    "emailAddress": "pmacnair21@vinaora.com", "phoneNumber": 20425254, "age": 63},
                   {"firstName": "Tina", "lastName": "Sclater", "gender": "m", "weight": 96, "city": "Kuala Terengganu",
                    "houseNumber": "33", "streetName": "Armistice", "zipCode": "1234AA",
                    "emailAddress": "tsclater22@bloglovin.com", "phoneNumber": 73376006, "age": 22},
                   {"firstName": "Umeko", "lastName": "Biesinger", "gender": "m", "weight": 71, "city": "Sztum",
                    "houseNumber": "13", "streetName": "Farmco", "zipCode": "1234AA",
                    "emailAddress": "ubiesinger23@mediafire.com", "phoneNumber": 74506564, "age": 39},
                   {"firstName": "Jeremias", "lastName": "Cancellario", "gender": "m", "weight": 67, "city": "Cimalati",
                    "houseNumber": "52114", "streetName": "Bowman", "zipCode": "1234AA",
                    "emailAddress": "jcancellario24@reddit.com", "phoneNumber": 77844212, "age": 26},
                   {"firstName": "Cassondra", "lastName": "Ridsdole", "gender": "m", "weight": 55, "city": "Shuibian",
                    "houseNumber": "3", "streetName": "Paget", "zipCode": "1234AA",
                    "emailAddress": "cridsdole25@spotify.com", "phoneNumber": 31606592, "age": 18},
                   {"firstName": "Raynor", "lastName": "Davydochkin", "gender": "m", "weight": 88, "city": "Fuquan",
                    "houseNumber": "6", "streetName": "Weeping Birch", "zipCode": "1234AA",
                    "emailAddress": "rdavydochkin26@google.com", "phoneNumber": 19080567, "age": 25},
                   {"firstName": "Ali", "lastName": "Coverley", "gender": "m", "weight": 81, "city": "Mojo",
                    "houseNumber": "79", "streetName": "Center", "zipCode": "1234AA",
                    "emailAddress": "acoverley27@nature.com", "phoneNumber": 55582518, "age": 19},
                   {"firstName": "Amalle", "lastName": "Orht", "gender": "m", "weight": 88, "city": "Mekarsari",
                    "houseNumber": "7", "streetName": "Northridge", "zipCode": "1234AA",
                    "emailAddress": "aorht28@sourceforge.net", "phoneNumber": 64187008, "age": 64},
                   {"firstName": "North", "lastName": "Elcoux", "gender": "m", "weight": 73, "city": "Aguas Corrientes",
                    "houseNumber": "7979", "streetName": "Beilfuss", "zipCode": "1234AA",
                    "emailAddress": "nelcoux29@bigcartel.com", "phoneNumber": 28835826, "age": 76},
                   {"firstName": "Axel", "lastName": "Foxen", "gender": "m", "weight": 51, "city": "Pengbu",
                    "houseNumber": "29", "streetName": "Sommers", "zipCode": "1234AA",
                    "emailAddress": "afoxen2a@pinterest.com", "phoneNumber": 59755376, "age": 36},
                   {"firstName": "Ekaterina", "lastName": "Stive", "gender": "m", "weight": 64, "city": "Bagnolet",
                    "houseNumber": "966", "streetName": "Corben", "zipCode": "1234AA",
                    "emailAddress": "estive2b@google.es", "phoneNumber": 48020685, "age": 18},
                   {"firstName": "Sawyer", "lastName": "Warlaw", "gender": "m", "weight": 79, "city": "Tiaong",
                    "houseNumber": "05", "streetName": "Kensington", "zipCode": "1234AA",
                    "emailAddress": "swarlaw2c@weibo.com", "phoneNumber": 71155449, "age": 28},
                   {"firstName": "Shelagh", "lastName": "O'Brien", "gender": "m", "weight": 77, "city": "Sfax",
                    "houseNumber": "6", "streetName": "Tony", "zipCode": "1234AA", "emailAddress": "sobrien2d@lulu.com",
                    "phoneNumber": 26405034, "age": 32},
                   {"firstName": "Giavani", "lastName": "Cresar", "gender": "m", "weight": 62, "city": "Greenville",
                    "houseNumber": "55585", "streetName": "Mcguire", "zipCode": "1234AA",
                    "emailAddress": "gcresar2e@opensource.org", "phoneNumber": 27938501, "age": 49},
                   {"firstName": "Charita", "lastName": "Mottinelli", "gender": "m", "weight": 62, "city": "Qvareli",
                    "houseNumber": "0", "streetName": "Ramsey", "zipCode": "1234AA",
                    "emailAddress": "cmottinelli2f@fda.gov", "phoneNumber": 68169896, "age": 54},
                   {"firstName": "Aile", "lastName": "Grimme", "gender": "m", "weight": 76, "city": "Tanahmerah",
                    "houseNumber": "919", "streetName": "Hollow Ridge", "zipCode": "1234AA",
                    "emailAddress": "agrimme2g@goo.ne.jp", "phoneNumber": 98684030, "age": 62},
                   {"firstName": "Danit", "lastName": "Maingot", "gender": "m", "weight": 68, "city": "Asquipata",
                    "houseNumber": "0", "streetName": "Dryden", "zipCode": "1234AA",
                    "emailAddress": "dmaingot2h@google.com", "phoneNumber": 94255459, "age": 52},
                   {"firstName": "Eda", "lastName": "Moland", "gender": "m", "weight": 52, "city": "Sandgerði",
                    "houseNumber": "99", "streetName": "La Follette", "zipCode": "1234AA",
                    "emailAddress": "emoland2i@oracle.com", "phoneNumber": 86246370, "age": 72},
                   {"firstName": "Emmye", "lastName": "Snelgrove", "gender": "m", "weight": 60, "city": "San Rafael",
                    "houseNumber": "3", "streetName": "Kensington", "zipCode": "1234AA",
                    "emailAddress": "esnelgrove2j@ted.com", "phoneNumber": 10602641, "age": 78},
                   {"firstName": "Alidia", "lastName": "Tibb", "gender": "m", "weight": 89, "city": "Bojongsari",
                    "houseNumber": "43", "streetName": "Warbler", "zipCode": "1234AA",
                    "emailAddress": "atibb2k@reddit.com", "phoneNumber": 14644042, "age": 66},
                   {"firstName": "Fabien", "lastName": "Benton", "gender": "m", "weight": 59, "city": "Uryupinsk",
                    "houseNumber": "0", "streetName": "Lyons", "zipCode": "1234AA",
                    "emailAddress": "fbenton2l@rakuten.co.jp", "phoneNumber": 21849059, "age": 27},
                   {"firstName": "Clint", "lastName": "Exposito", "gender": "m", "weight": 94, "city": "Simod",
                    "houseNumber": "44559", "streetName": "Nevada", "zipCode": "1234AA",
                    "emailAddress": "cexposito2m@cbsnews.com", "phoneNumber": 21869212, "age": 70},
                   {"firstName": "Otto", "lastName": "Summerside", "gender": "m", "weight": 82, "city": "That Phanom",
                    "houseNumber": "6031", "streetName": "Monica", "zipCode": "1234AA",
                    "emailAddress": "osummerside2n@nationalgeographic.com", "phoneNumber": 24245618, "age": 19},
                   {"firstName": "Filmore", "lastName": "Hanselmann", "gender": "m", "weight": 74, "city": "Guatimozín",
                    "houseNumber": "6", "streetName": "Twin Pines", "zipCode": "1234AA",
                    "emailAddress": "fhanselmann2o@flavors.me", "phoneNumber": 18649159, "age": 79},
                   {"firstName": "Charissa", "lastName": "Scopes", "gender": "m", "weight": 85, "city": "Hudai",
                    "houseNumber": "0", "streetName": "Twin Pines", "zipCode": "1234AA",
                    "emailAddress": "cscopes2p@weibo.com", "phoneNumber": 83158714, "age": 79},
                   {"firstName": "Lilllie", "lastName": "Ravelus", "gender": "m", "weight": 91, "city": "Fort Abbās",
                    "houseNumber": "5", "streetName": "Crowley", "zipCode": "1234AA",
                    "emailAddress": "lravelus2q@twitpic.com", "phoneNumber": 20659489, "age": 39},
                   {"firstName": "Cristionna", "lastName": "Wagstaff", "gender": "m", "weight": 50,
                    "city": "Staryy Merchyk", "houseNumber": "36", "streetName": "Calypso", "zipCode": "1234AA",
                    "emailAddress": "cwagstaff2r@economist.com", "phoneNumber": 45561725, "age": 34}]

        for member_data in members:
            member = Member()
            values = list(map(lambda x: str(x), member_data.values()))
            member.populate(values, member_data.keys())
            MemberRepository.persist_member(member)
